name: Deploy to Development Environment

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Create development .env
        run: cp .env.development .env.local

      - name: Build the site
        run: npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
        repo: vinopodnos/vinopodnos.github.io
        build_dir: build
        jekyll: false
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
