name: Deploy to Development Environment

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Create development .env
              run: cp .env.development .env.local

            - name: Set base domain do development environment
              run: echo "PUBLIC_URL=/website" >> .env.local

            - name: Build the library
              run: npm run build

            - name: Create .nojekyll
              run: touch build/.nojekyll

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-Deploy-action@3.7.1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  repository-name: vinopodnos/vinopodnos.github.io
                  branch: gh-pages
                  folder: build
                  clean: true
